name : Create Release

on : 
  push:
    branches:
      - release-*

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Build 
        run: |
          cd ./server 
          go build ./cmd/media-gallery
        
      - name: Create package folder to copy release items 
        run: |
          mkdir -p publish-folder/server
          cp -r ./client ./publish-folder 
          cp ./server/media-gallery ./publish-folder/server 
          cp ./server/dirs.txt ./publish-folder/server 
          tar -czf release.tar.gz -C ./publish-folder .

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
            name: Release-demo-${{ github.run_id }}
            path: "release.tar.gz"

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # asset_path: ./bin/azblogfilter.linux-amd64.tar.gz
          # asset_name: azblogfilter.linux-amd64.tar.gz
          asset_content_type: application/gzip
